import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ConvexClientProvider } from "@/components/web/ConvexClientProvider";
import { Toaster } from "sonner";
import 'highlight.js/styles/github-dark.css'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "google5ad45365b7d410b7",
  },
};


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "MutexBlog",
    template: "%s | MutexBlog",
  },
  description: "A specialized platform for technical discourse, focusing on core computer science, discrete mathematics, and advanced engineering principles.",
  authors: [{ name: "tastytaco", url: "https://nextblog-ov87.vercel.app" }],
  creator: "tastytaco",
  publisher: "MutexBlog",

  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://nextblog-ov87.vercel.app",
    siteName: "MutexBlog",
    title: "MutexBlog | Atomic Updates for Engineers",
    description: "Experience a seamless technical writing environment with real-time collaborative features and a modern developer-centric interface.",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "MutexBlog - Real-time Tech Blogging Platform",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "MutexBlog",
    description: "Atomic Updates for Engineers - Bridging the gap between code and content.",
    creator: "@KmaK69837720",
    images: ["/og-image.png"],
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  verification: {
    google: "OmzJnIQ1e1Pe6kyp3S7DL8AuEn0DuVUX80OCScnJ7io",
  },
  
  category: "technology",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="max-w-7xl mx-auto w-full px-4 md:px-6 lg:px-8">
              <ConvexClientProvider>{children}</ConvexClientProvider>
            </main>
            <Toaster richColors  />
          </ThemeProvider>
        
      </body>
    </html>
  );
}
